export const API_URL = {
    login: "/auth/login",
    register: "/auth/register",
    getMe: "/users/@me",
    getCompanyByUserUuid: "/companies/get-by-user/",
    getCompaniesByUserUuid: "/companies/get-companies-by-user/",
    getBranchesByCompanyUuid: "/branches/get-by-company-uuid/",
    getDivisionsByCompanyUuid: "/department-groups/get-all/dt",
    createDivisionByCompanyUuid: "/department-groups/create",
    updateDivisionByUuid: "/department-groups/update/",
    deleteDivisionByUuid: "/department-groups/delete/",
    getSubDivisionsByCompanyUuid: "/departments/get-all/dt",
    createSubDivisionByCompanyUuid: "/departments/create",
    updateSubDivisionByUuid: "/departments/update/",
    deleteSubDivisionByUuid: "/departments/delete/",
    createEmployeeByCompanyUuid: "/users/create",
    importEmployee: "/users/import",
    createEmployeeHistory: "/employment-histories/create",
    getEmployeeByCompanyUuid: "/users/get-all/dt",
    updateEmployeeByUuid: "/users/update/",
    exportEmployeeToExcel: "/users/export",
    getRolesByCompanyUuid: "/roles/get-all/dt"
}