export const API_URL = {
  login: "/auth/login",
  register: "/auth/register",
  getMe: "/users/@me",
  updateUser: "/users/update/",
  getCompanyByUserUuid: "/companies/get-by-user/",
  getCompaniesByUserUuid: "/companies/get-companies-by-user/",
  getCompanyByUuid: "/companies/get/",
  getBranchesByCompanyUuid: "/branches/get-by-company-uuid/",
  getDivisionsByCompanyUuid: "/department-groups/get-all/dt",
  createDivisionByCompanyUuid: "/department-groups/create",
  updateDivisionByUuid: "/department-groups/update/",
  deleteDivisionByUuid: "/department-groups/delete/",
  getSubDivisionsByCompanyUuid: "/departments/get-all/dt",
  createSubDivisionByCompanyUuid: "/departments/create",
  updateSubDivisionByUuid: "/departments/update/",
  deleteSubDivisionByUuid: "/departments/delete/",
  createEmployeeByCompanyUuid: "/users/create",
  assignEmployeeToSubDivision: "/users/update-department/",
  unassignEmployeeFromSubDivision: "/users/remove-from-department/",
  terminateUser: "/users/delete/",
  rehireUserByUuid: "/users/rehire/",
  importEmployee: "/users/import",
  createEmployeeHistory: "/employment-histories/create",
  getEmployeeByCompanyUuid: "/users/get-all/dt",
  updateEmployeeByUuid: "/users/update/",
  exportEmployeeToExcel: "/users/export",
  getRolesByCompanyUuid: "/roles/get-all/dt",
  createBranchByCompanyUuid: "/branches/create",
  updateBranchByUuid: "/branches/update/",
  deleteBranchByUuid: "/branches/delete/",

  attendanceListAll: "/attendance/list-all",

  // for employee (self)
  attendanceClockIn: "/attendance/clock-in",
  attendanceClockOut: "/attendance/clock-out",
  attendanceToggleHomeOffice: "/attendance/toggle-homeOffice",
  attendanceSaveNotes: "/attendance/notes",
  attendanceGetByDate: "/attendance",
  attendanceListRange: "/attendance/range",
  attendanceListCalendar: "/attendance/calendar",
  attendanceEditRequests: "/attendance/edit-requests",
  attendanceEditRequestsMy: "/attendance/edit-requests/my",
  employeeProfileSelf: "/employee/me",

  departmentList: "/departments",
  departmentGroupList: "/department-groups",
};
